I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    show polar with dissolve(0.5)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    show polar with dissolve(0.5)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1678, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\exports.py", line 1758, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 2978, in do_with
    return self.interact(trans_pause=True,
  File "D:\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 3976, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 3922, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
pisuuun 1.0
Wed Dec 20 12:29:31 2023
